version: '2'

plugins:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .vue
        - .ts
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - BUG

  editorconfig:
    enabled: true

  nodesecurity:
    enabled: true
