nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN-false}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
