yarnPath: ".yarn/releases/yarn-berry.js"
nodeLinker: node-modules
npmRegistryServer: https://npm.dreamnet.tech

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
