nodeLinker: node-modules

npmRegistryServer: "https://npm.dreamnet.tech"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.0.0-rc.36.js
