name: "@dreamnettech/app"
on:
  push:
    paths:
      - workspaces/app/src/**

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Setup
        working-directory: workspaces/app
        run: yarn install

      - name: Build
        working-directory: workspaces/app
        run: yarn run build

      - name: Publish
        working-directory: workspaces/app
        run: yarn npm publish --tolerate-republish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
