name: "build"

on:
  workflow_dispatch:
  push:
    tags: [ build-v* ]

jobs:
  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
    with:
      checkout: true
      working-dir: workspaces/build
