name: "@dreamnet/deploy"

on:
  workflow_dispatch:
  push:
    paths:
      - workspaces/deploy/**.js
      - workspaces/deploy/**.ts
    branches:
      - master
  
env:
  WORK_DIR: workspaces/deploy
  NODE_ENV: production

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: monorepo-cache
        with:
          path: |
            node_modules
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: ⚙️ Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 👨🏻‍💻 Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: yarn install

      - name: 🚀 Publish
        working-directory: ${{ env.WORK_DIR }}
        run: yarn npm publish --access public --tolerate-republish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
