name: "@dreamnet/deploy"

on:
  push:
    paths:
      - workspaces/deploy/**.js
      - workspaces/deploy/**.ts
      - workspaces/deploy/**.json
  workflow_dispatch:

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        working-directory: workspaces/deploy
        run: yarn install

      - name: Publish
        working-directory: workspaces/deploy
        run: yarn npm publish --access public --tolerate-republish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
