name: "deploy"

on:
  workflow_dispatch:
  push:
    tags: [ deploy-v* ]

env:
  WORK_DIR: workspaces/deploy
  NODE_ENV: production

jobs:
  # Build source
  build:
    uses: ./.github/workflows/template.build-node.yml
    secrets: inherit
    with:
      working-dir: workspaces/deploy
      build-command: |
        yarn workspace @opendreamnet/app build
        yarn run build

  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
