name: "eslint-config"

on:
  workflow_dispatch:
  push:
    tags: [ eslint-config-v* ]

jobs:
  # Build source
  build:
    uses: ./.github/workflows/template.build-node.yml
    secrets: inherit
    with:
      working-dir: workspaces/eslint-config

  # Publish on NPM
  publish:
    needs: build
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
    with:
      working-dir: workspaces/eslint-config
