name: "ipfs"

on:
  workflow_dispatch:
  push:
    tags: [ ipfs-v* ]

jobs:
  # Build source
  build:
    uses: ./.github/workflows/template.build-node.yml
    secrets: inherit
    with:
      working-dir: workspaces/ipfs
      lint: true
      build-command: |
        yarn workspace @opendreamnet/app build
        yarn run build

  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
