name: "@dreamnet/logplease (legacy)"

on:
  workflow_dispatch:
  push:
    paths:
      - workspaces/logplease/**.js
      - workspaces/logplease/**.ts
  
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: monorepo-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: ⚙️ Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 👨🏻‍💻 Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: yarn install

      - name: 🏗️ Build
        working-directory: ${{ env.WORK_DIR }}
        run: yarn run build

      - name: 🚀 Publish
        working-directory: ${{ env.WORK_DIR }}
        run: yarn npm publish --access public --tolerate-republish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
