name: "nuxtjs-base"

on:
  workflow_dispatch:
  push:
    tags: [ nuxtjs-base-v* ]

jobs:
  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
    with:
      checkout: true
      working-dir: workspaces/nuxtjs-base
