name: "queue"

on:
  workflow_dispatch:
  push:
    tags: [ queue-v* ]

jobs:
  # Build source
  build:
    uses: ./.github/workflows/template.build-node.yml
    secrets: inherit
    with:
      working-dir: workspaces/queue
      lint: true

  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
