name: retry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags: [ retry-v* ]

env:
  WORK_DIR: workspaces/retry
  NODE_ENV: production

jobs:
  # Build source
  build:
    uses: ./.github/workflows/template.build-node.yml
    secrets: inherit
    with:
      working-dir: workspaces/retry

  # Publish on NPM
  publish:
    uses: ./.github/workflows/template.publish.yml
    secrets: inherit
