name: retry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags: [ retry-v* ]

env:
  WORK_DIR: workspaces/retry
  NODE_ENV: production

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v3

      - name: 📦 Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: monorepo-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: ⚙️ Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 👨🏻‍💻 Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: yarn install

      - name: 🏗️ Build
        working-directory: ${{ env.WORK_DIR }}
        run: yarn run build

      - name: 🚀 Publish
        working-directory: ${{ env.WORK_DIR }}
        run: yarn npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
